service: aws-python-scheduled-cron-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-2

functions:
  hello:
    handler: handler.hello
    vpc:
      securityGroupIds:
        -  ### YOUR SECURITY GROUP ID ###
      subnetIds:
        -  ### YOUR SUBNET ID ###
        -  ### YOUR SUBNET ID ###
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 hour)
  # cronHandler:
  #   handler: handler.run
  #   events:
  #     # Invoke Lambda function every 2nd minute from Mon-Fri
  #     - schedule: cron(0/2 * ? * MON-FRI *)
